### ISSUE TITLE
Allow selecting speed/heart rate target for workout download

### ISSUE THREAD

**Issue by abs0** [TrainAsONE/trainasone-connectiq#1]
A user's profile allows selection of a default preference for speed or heart rate target, but the FIT/TCX download page allows this to be overridden.

The Garmin ConnectIQ widget should provide a similar option to override the target

**Comment by YoungYoungs** [comment]
This feature would be great. Is this likely to happen anytime soon?

**Comment by abs0** [comment]
Its definitely near the top of our list of changes for the ConnectIQ app. We'll see if we can schedule it sooner rather than later!

Thanks

David

**Comment by YoungYoungs** [comment]
Hi, sorry I wrote this before finding out how to change the global setting
to allow HR workout downloads. This is fine for me now although the feature
would be handy. I made a comment on Garmin connect about documenting the
global setting on the widget homepage. This all makes TAO far more usable.
Good work.

**Comment by abs0** [comment]
Added in 0.0.13
