### ISSUE TITLE
Unable to download workouts (IQ! error) after sign-in process completes (Fenix 5x)

### ISSUE THREAD

**Issue by nickccox** [TrainAsONE/trainasone-connectiq#11]
Each time I try to use the latest app I'm asked to grant access on my phone, after granting access the app encounters some error downloading a workout. Retrying causes the access grant to be requested again...loop forever.

Logs suggest a type mismatch - string expected, number given.
[CIQ_LOG.TXT](https://github.com/TrainAsONE/trainasone-connectiq/files/1334597/CIQ_LOG.TXT)

For completeness - here are my steps to recreate:

On Mac - Connected watch via USB
On Mac - Deleted original app file
On Mac - Copied new app (0.03) to Fenix 5X
On Mac - Disconnected watch
On Watch - Paged through IQ apps to select TAO app
On Watch - New app UX renders (looks lovely!) and screen displays 'Please grant access to TrainAsOne on your phone' (paginated perfectly).
On Android phone - I tap the ConnectIQ notification.
On Android phone - Connect app says 'Sign in process complete. Return to your Garmin device.'
On Watch - 'Downloading Workout' is displayed briefly
On Watch - IQ logo with orange exclamation mark renders.

**Comment by abs0** [comment]
*Many* thanks for this Nick - we've been able to track it down to an issue with the Garmin SDK which unfortunately does not show up on the simulator, only on real devices.

We have a workaround and will be sending out updated binaries shortly.

Thanks again!
